language: android
jdk: oraclejdk8
sudo: false

addons:
  sonarqube: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - "./gradlew build connectedCheck --stacktrace"
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
